// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Application struct {
	ID            pgtype.UUID
	UserID        string
	JobTitle      string
	Company       string
	Url           string
	Source        int16
	Status        int16
	AppliedAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	SchemaVersion string
}
