// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertApplication = `-- name: InsertApplication :one
INSERT INTO applications (
    user_id, job_title, company, url, source, status, applied_at, schema_version
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, user_id, job_title, company, url, source, status, applied_at, created_at, schema_version
`

type InsertApplicationParams struct {
	UserID        string
	JobTitle      string
	Company       string
	Url           string
	Source        int16
	Status        int16
	AppliedAt     pgtype.Timestamptz
	SchemaVersion string
}

func (q *Queries) InsertApplication(ctx context.Context, arg InsertApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, insertApplication,
		arg.UserID,
		arg.JobTitle,
		arg.Company,
		arg.Url,
		arg.Source,
		arg.Status,
		arg.AppliedAt,
		arg.SchemaVersion,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobTitle,
		&i.Company,
		&i.Url,
		&i.Source,
		&i.Status,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.SchemaVersion,
	)
	return i, err
}

const getApplicationByIDAndUserID = `-- name: GetApplicationByIDAndUserID :one
SELECT id, user_id, job_title, company, url, source, status, applied_at, created_at, schema_version
FROM applications
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetApplicationByIDAndUserIDParams struct {
	ID     pgtype.UUID
	UserID string
}

func (q *Queries) GetApplicationByIDAndUserID(ctx context.Context, arg GetApplicationByIDAndUserIDParams) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationByIDAndUserID, arg.ID, arg.UserID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobTitle,
		&i.Company,
		&i.Url,
		&i.Source,
		&i.Status,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.SchemaVersion,
	)
	return i, err
}

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO outbox (aggregate_id, topic, payload)
VALUES ($1, $2, $3)
`

type InsertOutboxParams struct {
	AggregateID pgtype.UUID
	Topic       string
	Payload     []byte
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.Exec(ctx, insertOutbox, arg.AggregateID, arg.Topic, arg.Payload)
	return err
}
